apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: {{ .Values.environment }}-backend-sa
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888
          env:
            - name: DYNAMODB_ENDPOINT
              value: {{ .Values.dynamodb.endpoint | quote }}
            - name: DYNAMODB_TABLE
              value: {{ .Values.dynamodb.table | quote }}
            {{- if eq .Values.environment "local" }}
            - name: AWS_ACCESS_KEY_ID
              value: fake
            - name: AWS_SECRET_ACCESS_KEY
              value: fake
            - name: AWS_REGION
              value: {{ .Values.dynamodb.region | default "eu-west-1" | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
