apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 8888
      protocol: TCP
      {{- if eq .Values.environment "local" }}
      nodePort: 30080
      {{- end }}
    - name: https
      port: 443
      targetPort: 8888
      protocol: TCP
      {{- if eq .Values.environment "local" }}
      nodePort: 30443
      {{- end }}
