apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.environment }}-backend-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.aws.irsa.enabled }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.aws.irsa.roleName }}
    {{- end }}
