name: Download Code Artifact
description: Download the repo code artifact
inputs:
  artifact-name:
    description: 'Name of the artifact to download'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download code artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: .
