services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"

  hello-app:
    image: hello-world-cloud-app
    container_name: hello-world-cloud-app
    ports:
      - "8888:8888"
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: eu-west-1
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
