name: Upload Code Artifact
description: Upload the repo code artifact
inputs:
  artifact-name:
    description: "Name of the uploaded artifact"
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload code artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: .
