name: 1 - AWS Terraform - Init and Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (e.g., dev, staging, prod)"
        required: true
        default: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  init_plan_aws:
    name: Init and Plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.11.4
    env:
      ENV: ${{ inputs.environment }}
      AWS_REGION: eu-west-1
      AWS_ROLE_TO_ASSUME: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan AWS
        working-directory: terraform/aws
        run: |
          terraform init -reconfigure
          terraform workspace select ${{ env.ENV }} || terraform workspace new ${{ env.ENV }}
          terraform plan -var-file=../env/${{ env.ENV }}.tfvars -out=plan.out
